### ISSUE TITLE
No module named 'utils'

### ISSUE THREAD

**Issue by karmahah** [DunnCreativeSS/CryptoFuturesHedgingWithBlackScholesOptions#1]
Hello, 
Python3 on Debian 9.0 -  I installed deribit api via pip3

I get: 
`Traceback (most recent call last):
  File "CryptoFuturesHedgingWithBlackScholesOptions/app.py", line 8, in <module>
    from utils          import ( get_logger, lag, print_dict, print_dict_of_dicts, sort_by_key,
ModuleNotFoundError: No module named 'utils'
`

**Comment by staccDOTsol** [comment]
Hi!

I've updated the repo with the utils.py and util directory. I think it should work now.

Sorry for any inconvenience!

Feel free to join our Telegram: https://t.me/ManyVolumeSignalMonster

Or read my blog: https://jare.cloud
